name: meet1350
description: Meet 1350
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_flavorizr: ^2.2.3
  equatable: ^2.0.5
  get: ^4.6.6
  flutter_native_splash: ^2.4.1

dev_dependencies:
  analyzer: ^6.2.0
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/flutter_gen_assets
  assets:
    enabled: true

flutter:
  assets:
    - assets/images/
  uses-material-design: true
flavorizr:
  flavors:
    dev:
      app:
        name: '[dev] meet1350'
      android:
        applicationId: 'com.paulyswen.meet1350.dev'
        firebase:
          config: '.firebase/dev/google-services.json'
        customConfig:
          minSdkVersion: 26
          targetSdkVersion: 33
      ios:
        bundleId: 'com.paulyswen.meet1350.dev'
        firebase:
          config: '.firebase/dev/GoogleService-Info.plist'
    qat:
      app:
        name: '[qat] meet1350'
      android:
        applicationId: 'com.paulyswen.meet1350.qat'
        firebase:
          config: '.firebase/qat/google-services.json'
        customConfig:
          minSdkVersion: 26
          targetSdkVersion: 33
      ios:
        bundleId: 'com.paulyswen.meet1350.qat'
        firebase:
          config: .firebase/qat/GoogleService-Info.plist
    prod:
      app:
        name: 'meet1350'
      android:
        applicationId: 'com.paulyswen.meet1350'
        firebase:
          config: '.firebase/prod/google-services.json'
        customConfig:
          minSdkVersion: 26
          targetSdkVersion: 33
      ios:
        bundleId: com.paulyswen.meet1350
        firebase:
          config: .firebase/prod/GoogleService-Info.plist